### ISSUE TITLE
Simplify the internals of our `sizes` function

### ISSUE THREAD

**Issue by joemcgill** [joemcgill/develop.wordpress#4]
_copied from an inline comment on #2_

The args parameter is a set of arguments that can be passed to the the sizes function to customize the markup. When I originally wrote this function, I was thinking in terms of building an API that allows people to build an array of sizes, which would be converted into a properly formatted sizes value. Using a generic $args value seems to be a common pattern throughout WordPress and gave us some flexibility to change the input options as needed.

In practice, I've wondered if this whole function is over engineered and if we would be better served to drop the ability to build your own pattern, only build the default sizes attribute, and let devs filter the value however they like. If so, this function could be greatly simplified.

**Comment by jaspermdegroot** [comment]
@joemcgill 

I am in favor of dropping the `$args` parameter and simplifying the sizes function.
The only case that I can think of where the parameter has benefits compared to the filter is when calling the function directly (template tag). Then you know the location/context of the image and could adjust the value of the `sizes` attribute to that.

We could replace the `$args` parameter by a `$context` (or `$location`) parameter which we would pass to the filter so you can still achieve the same thing.

This would have another benefit. Currently the sizes function uses the same defaults for images in the content and for featured images / galleries because it has no idea by which internal function it has been called.

```
$defaults = array(
    'sizes' => array(
        array(
            'size_value' => '100vw',
            'mq_value'   => $img_width,
            'mq_name'    => 'max-width'
        ),
        array(
            'size_value' => $img_width
        ),
    )
);
```

In case of images in the content it would be better if we check if image width is larger than the global `$content_width` and, if so, use the content width instead of image width. We can do this by setting "content" as argument for `$context` when we call the sizes function and add something like `if ( "content" === $context && $img_width > $content_width ) { ... }`.

**Comment by joemcgill** [comment]
I like the idea of having an argument for flagging whether the image size should be modified by `image_constrain_size_for_editor()`. And I tend to agree that the only times the full argument would be useful is on occasions where you already know the `sizes` value you're trying to produce.

**Comment by jaspermdegroot** [comment]
@joemcgill 

I opened PR https://github.com/joemcgill/develop.wordpress/pull/7 where commit https://github.com/jaspermdegroot/develop.wordpress/commit/71f751a865a9e9c0552e68ef3d8b1dbe62abcfa4 simplifies the internals of the sizes function.
After looking into it I came to the conclusion that there is no need to call `image_constrain_size_for_editor`. See https://github.com/jaspermdegroot/develop.wordpress/commit/95eca8d89989a9b6efa79624517dc9a90b8909f7.

**Comment by joemcgill** [comment]
I used most of the ideas in #7 and simplified the internals a step further in #8.

**Comment by jaspermdegroot** [comment]
@joemcgill 

I was reading my previous [comment](https://github.com/joemcgill/develop.wordpress/issues/4#issuecomment-145336888) again where I suggested to add a `$context` param to the sizes function and its filter. Looking at the code as it is now and thinking of the actual use cases I had in mind I don't think we need this anymore.
So I guess everything in this ticket has been covered and it can be closed.

**Comment by joemcgill** [comment]
> Looking at the code as it is now and thinking of the actual use cases I had in mind I don't think we need this anymore.

I was thinking the same thing. Since we're no longer generating the `srcset` and `sizes` attributes inside the editor, we can leave this as is and devs can filter the output if they need to constrain the width of an image to the `$content_width` value.
